
services:
  database:
    image: postgres:15-alpine
    container_name: monitor-postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=monitor_user
      - POSTGRES_PASSWORD=monitor_password
      - POSTGRES_DB=monitor_db
      - TZ=Asia/Bangkok
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-network

  backend:
    build:
      context: ./backend
    container_name: monitor-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=monitor_user
      - DB_PASSWORD=monitor_password
      - DB_NAME=monitor_db
      - DB_SSLMODE=disable
      - JWT_SECRET_KEY=yoursupersecurejwtsecretkey
      - N8N_WEBHOOK_URL=http://localhost:5678/webhook/api-healthcheck
    depends_on:
      - database
    networks:
      - monitor-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://203.151.56.27:8082
    container_name: monitor-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  postgres_data:
